version: '3'
services:
  app:
    environment:
      - REDIS_URL=redis://cache # TODO: add actual path
      - NODE_ENV=production
      - PORT=3000
    command:
      sh -c 'npx webpack --mode=production'
